#!/bin/bash

function usage()
{
	echo "Usage: $0 [ -h | --help] [ -c | --config CONFIG_FILE ]"
	exit 0
}

options=$(getopt -q -o hc: --long help,config: -- "$@")
if [ $? -ne 0 ]; then
	echo "Invaild option!"
	usage
fi

eval set -- "$options"
conf="/etc/sysconfig/readahead_tune.conf"

while true;
do
	case "$1" in
		-h | --help)
			usage ;;
		-c | --config)
			conf="$2"
			shift 2 ;;
		-- )
			shift
			break ;;
		* )
			echo "Unexpected option: $1 - this should not happen."
			usage ;;
	esac
done

/usr/sbin/readahead_tune -v -c $conf
